# Generated by Django 5.0.7 on 2024-09-16 11:04

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(validators=[authentication.validators.validate_minimum_age]),
        ),
    ]
